// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs-T4KfBq73VY_n6VOjzaU2Cxt2X7SrCQ',
    appId: '1:348892999903:web:9bda8c495e670ab107796a',
    messagingSenderId: '348892999903',
    projectId: 'ecommerce-26b18',
    authDomain: 'ecommerce-26b18.firebaseapp.com',
    databaseURL: 'https://ecommerce-26b18-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-26b18.appspot.com',
    measurementId: 'G-V2WQ3PW5XJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW_so_r7fO1JPFN2e_boIYw5KVhFiF2rM',
    appId: '1:348892999903:android:e78ad7153b805f9707796a',
    messagingSenderId: '348892999903',
    projectId: 'ecommerce-26b18',
    databaseURL: 'https://ecommerce-26b18-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-26b18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr56oTn29jyaRVWfUZB8i2m1LSG2-nXGQ',
    appId: '1:348892999903:ios:7d17ab64d7414ca207796a',
    messagingSenderId: '348892999903',
    projectId: 'ecommerce-26b18',
    databaseURL: 'https://ecommerce-26b18-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-26b18.appspot.com',
    androidClientId: '348892999903-1s6rf99hed6cs3g5k7kmjo6grje0njnk.apps.googleusercontent.com',
    iosClientId: '348892999903-b7f25tsrsnsb4ndq7af4a63772nqmavc.apps.googleusercontent.com',
    iosBundleId: 'com.diatus.subgkartDelivery',
  );
}
