// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'this app does not ship a web build.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_YMZV4Zny306NUTmNNijeE7gCGs0eK4A',
    appId: '1:135817720188:android:9328ba04d750dbe9a3b4f9',
    messagingSenderId: '135817720188',
    projectId: 'vaibhav-s-ecommerce-app',
    databaseURL: 'https://vaibhav-s-ecommerce-app.firebaseio.com',
    storageBucket: 'vaibhav-s-ecommerce-app.appspot.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmyXoI36rVHsDRl4RE9j4JwWhedEX96pc',
    appId: '1:135817720188:ios:40b650ee4504c14da3b4f9',
    messagingSenderId: '135817720188',
    projectId: 'vaibhav-s-ecommerce-app',
    databaseURL: 'https://vaibhav-s-ecommerce-app.firebaseio.com',
    storageBucket: 'vaibhav-s-ecommerce-app.appspot.com',
    iosClientId: '135817720188-dcu5tssskid6ol2salnm5uj40i2ngjmf.apps.googleusercontent.com',
    iosBundleId: 'com.diatus.localBazaarDelivery',
  );
}
